---
- name: Installing apt Packages (Git)
  ansible.builtin.apt:
    pkg: "git"
    state: present
# only available in rpm format as of 6/15/20
#- name: Installing apt Packages (Git Cred Manager)
#  apt:
#    pkg: "git-credential-manager"
#    state: present