---
- name: Do git config (http.sslVerify)
  community.general.git_config:
    name: http.sslVerify
    scope: "{{ git_config_scope }}"
    value: "{{ git_ssl_verify }}"

- name: Do git config - email
  community.general.git_config:
    name: user.email
    scope: "{{ git_config_scope }}"
    value: "{{ git_user_email }}"

- name: Do git config - name
  community.general.git_config:
    name: user.name
    scope: "{{ git_config_scope }}"
    value: "\"{{ git_user_full_name }}\""