---
- name: Add bash-completion to bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'source /usr/local/etc/profile.d/bash_completion.sh'
    create: yes

- name: Add show dirty state to bash_profile
  lineinfile:
    path: ~/.bash_profile
    line: 'GIT_PS1_SHOWDIRTYSTATE=true'
    create: yes

- name: Configure .gitexcludes
  lineinfile:
    path: ~/.gitexcludes
    line: .DS_Store
    create: yes

- name: Do git config (http.sslVerify)
  git_config:
    name: http.sslVerify
    scope: global
    value: "{{ git_ssl_verify }}"

- name: Do git config (user.email)
  git_config:
    name: user.email
    scope: global
    value: "{{ user_email }}"

- name: Do git config (user.name)
  git_config:
    name: user.name
    scope: global
    value: "\"{{ user_name }}\""